---
- name: Ensure chrony Installed
  ansible.builtin.apt:
    name: chrony
    state: present
- name: Ensure systemd-timesyncd Removed
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: absent
    purge: true
    autoremove: true
- name: Ensure chrony Service
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
- name: Ensure /etc/chrony Exists
  ansible.builtin.file:
    path: /etc/chrony
    state: directory
    mode: '0755'
- name: Find Files in /etc/chrony
  ansible.builtin.find:
    paths: /etc/chrony
    excludes: [chrony.conf]
    hidden: true
    file_type: any
  register: ntp_chrony_extra_files
- name: Wipe Extra Files in /etc/chrony
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: absent
  loop: '{{ ntp_chrony_extra_files.files }}'
  notify: Restart chrony Service
- name: Copy chrony.conf
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart chrony Service
