---
auditd_packages: [auditd, audispd-plugins]
auditd_watches:
  - {path: /etc/localtime, key: time-change, kind: file, perm: wa}
  - {path: /etc/issue, key: system-locale, kind: file, perm: wa}
  - {path: /etc/issue.net, key: system-locale, kind: file, perm: wa}
  - {path: /etc/hostname, key: system-locale, kind: file, perm: wa}
  - {path: /etc/hosts, key: system-locale, kind: file, perm: wa}
  - {path: /etc/nsswitch.conf, key: system-locale, kind: file, perm: wa}
  - {path: /etc/network/interfaces, key: system-locale, kind: file, perm: wa}
  - {path: /etc/network/interfaces.d, key: system-locale, kind: dir, perm: wa}
  - {path: /etc/apparmor, key: MAC-policy, kind: dir, perm: wa}
  - {path: /etc/apparmor.d, key: MAC-policy, kind: dir, perm: wa}
  - {path: /etc/sudoers, key: scope, kind: file, perm: wa}
  - {path: /var/log/sudo.log, key: sudo_log_file, kind: file, perm: wa}
  - {path: /etc/group, key: identity, kind: file, perm: wa}
  - {path: /etc/passwd, key: identity, kind: file, perm: wa}
  - {path: /etc/gshadow, key: identity, kind: file, perm: wa}
  - {path: /etc/shadow, key: identity, kind: file, perm: wa}
  - {path: /etc/security/opasswd, key: identity, kind: file, perm: wa}
  - {path: /etc/pam.conf, key: identity, kind: file, perm: wa}
  - {path: /etc/pam.d, key: identity, kind: dir, perm: wa}
  - {path: /var/run/utmp, key: session, kind: file, perm: wa}
  - {path: /var/log/wtmp, key: session, kind: file, perm: wa}
  - {path: /var/log/btmp, key: session, kind: file, perm: wa}
  - {path: /var/log/lastlog, key: logins, kind: file, perm: wa}
  - {path: /var/run/faillock, key: logins, kind: dir, perm: wa}
  - {path: /usr/bin/chcon, key: perm_chng, kind: file, perm: x}
  - {path: /usr/bin/setfacl, key: perm_chng, kind: file, perm: x}
  - {path: /usr/bin/chacl, key: perm_chng, kind: file, perm: x}
  - {path: /usr/sbin/usermod, key: usermod, kind: file, perm: x}
  - {path: /usr/bin/kmod, key: kernel_modules, kind: file, perm: x}
auditd_tools:
  - /sbin/auditctl
  - /sbin/aureport
  - /sbin/ausearch
  - /sbin/auditd
  - /sbin/augenrules
