---
chrony_pools:
  - za.pool.ntp.org iburst maxsources 3
chrony_servers:
  - time.cloudflare.com iburst NTS
chrony_directives:
  - makestep 1.0 3
  - driftfile /var/lib/chrony/drift
  - rtcsync
chrony_conflicting_packages:
  - systemd-timesyncd
