---
ssh_server_config:
  PermitRootLogin: prohibit-password
  PasswordAuthentication: "no"
  PubkeyAuthentication: "yes"
  PermitEmptyPasswords: "no"
  PermitUserEnvironment: "no"
  UsePAM: "yes"
  GSSAPIAuthentication: "no"
  HostbasedAuthentication: "no"
  IgnoreRhosts: "yes"
  DisableForwarding: "yes"
  AllowTcpForwarding: "no"
  AllowAgentForwarding: "no"
  LoginGraceTime: "60"
  LogLevel: "VERBOSE"
  MaxAuthTries: "3"
  MaxSessions: "10"
  MaxStartups: "10:30:60"
  ClientAliveInterval: "15"
  ClientAliveCountMax: "2"
  Banner: "/etc/issue.net"
  PrintMotd: "no"
  AuthorizedKeysFile: ".ssh/authorized_keys"
ssh_server_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr
ssh_server_kex_algorithms:
  - mlkem768x25519-sha256
  - sntrup761x25519-sha512
  - curve25519-sha256
  - curve25519-sha256@libssh.org
  - diffie-hellman-group16-sha512
  - diffie-hellman-group18-sha512
  - diffie-hellman-group14-sha256
ssh_server_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
