---
- name: Ensure AIDE Packages are Installed
  ansible.builtin.apt:
    name: [aide, aide-common]
    state: present
- name: Check for the AIDE Database
  ansible.builtin.stat:
    path: "/var/lib/aide/aide.db"
    get_checksum: false
    get_mime: false
    get_attributes: false
  register: aide_database
- name: Protect audit-tool Integrity in the Config
  ansible.builtin.template:
    src: cis-audit-tools.j2
    dest: "/etc/aide/aide.conf.d/70_cis_audit_tools"
    owner: root
    group: root
    mode: "0644"
  register: aide_audit_tools_confd
- name: Initialise or Rebuild the AIDE Database
  ansible.builtin.command: aideinit -y -f
  changed_when: true
  when:
    - not aide_database.stat.exists or (aide_audit_tools_confd.changed | default(false))
- name: Ensure the Daily AIDE Check Timer is Unmasked, Enabled and Active
  ansible.builtin.systemd_service:
    name: "dailyaidecheck.timer"
    masked: false
    enabled: true
    state: started
