---
- name: Ensure Access to passwd/group/shells Files is Configured
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: file
    owner: root
    group: root
    mode: "0644"
  loop: [passwd, passwd-, group, group-, shells]
- name: Ensure Access to shadow/gshadow Files is Configured
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: file
    owner: root
    group: shadow
    mode: "0640"
  loop: [shadow, shadow-, gshadow, gshadow-]
- name: Check for /etc/security/opasswd and its Backup
  ansible.builtin.stat:
    path: "/etc/security/{{ item }}"
  register: system_file_perms_opasswd
  loop: [opasswd, opasswd.old]
- name: Ensure Access to /etc/security/opasswd is Configured
  ansible.builtin.file:
    path: "/etc/security/{{ item.item }}"
    state: file
    owner: root
    group: root
    mode: "0600"
  loop: "{{ system_file_perms_opasswd.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: item.stat.exists
