---
- name: Ensure at is Removed
  ansible.builtin.apt:
    name: at
    state: absent
    purge: true
    autoremove: true
- name: Ensure cron is Installed
  ansible.builtin.package:
    name: "cron"
    state: present
- name: Ensure cron Daemon is Unmasked, Enabled, and Active
  ansible.builtin.systemd_service:
    name: "cron"
    masked: false
    enabled: true
    state: started
- name: Ensure Access to /etc/crontab is Configured
  ansible.builtin.file:
    path: /etc/crontab
    state: file
    owner: root
    group: root
    mode: "0600"
- name: Ensure Access to System cron Directories is Configured
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
  loop: "{{ job_schedulers_cron_dirs }}"
- name: Ensure /etc/cron.allow Exists and is Restricted
  ansible.builtin.copy:
    dest: /etc/cron.allow
    content: ""
    owner: root
    group: "root"
    mode: "0640"
- name: Ensure /etc/cron.deny is Absent
  ansible.builtin.file:
    path: /etc/cron.deny
    state: absent
