---
- name: Ensure at is Removed
  ansible.builtin.apt:
    name: at
    state: absent
- name: Ensure cron is Installed
  ansible.builtin.apt:
    name: cron
    state: present
- name: Ensure cron Service
  ansible.builtin.service:
    name: cron
    state: started
    enabled: true
- name: Ensure /etc/crontab Permissions
  ansible.builtin.file:
    path: /etc/crontab
    state: file
    owner: root
    group: root
    mode: '0600'
- name: Ensure Cron Directory Permissions
  ansible.builtin.file:
    path: /etc/cron.{{ item }}
    state: directory
    owner: root
    group: root
    mode: '0700'
  loop: [hourly, daily, weekly, monthly, yearly, d]
- name: Ensure /etc/cron.allow Exists
  ansible.builtin.file:
    path: /etc/cron.allow
    state: touch
    modification_time: preserve
    access_time: preserve
    owner: root
    group: root
    mode: '0600'
