---
- name: Rebuild exim4 config
  ansible.builtin.command: update-exim4.conf
  changed_when: true
  listen: Rebuild exim4 config
  notify: Restart exim4

- name: Restart exim4
  ansible.builtin.systemd_service:
    name: exim4
    state: restarted
  listen: Restart exim4

- name: Restart postfix
  ansible.builtin.systemd_service:
    name: postfix
    state: restarted
  listen: Restart postfix
