---
- name: Load Audit Rules
  ansible.builtin.command: augenrules --load
  changed_when: true
  listen: Load Audit Rules
- name: Regenerate the GRUB Configuration
  ansible.builtin.command: "update-grub"
  changed_when: true
  listen: Regenerate Grub
- name: Materialise faillock
  ansible.builtin.command: systemd-tmpfiles --create /etc/tmpfiles.d/audit-faillock.conf
  changed_when: true
  listen: Materialise faillock
- name: Restart auditd
  ansible.builtin.systemd_service:
    name: "auditd"
    state: restarted
  listen: Restart auditd
