---
- name: Change Root Password
  hosts: proxmox
  vars: {ansible_password: 'password'}
  tasks:
    - name: Change Root Password
      ansible.builtin.user:
        name: root
        password: '{{ root_password_hash }}'
        update_password: always
