---
- name: Change Root Password
  hosts: proxmox
  vars_prompt:
    - name: ansible_password
      prompt: Current Password
      private: true
  tasks:
    - name: Change Root Password
      ansible.builtin.user:
        name: root
        password: '{{ root_password_hash }}'
        update_password: always
