---
- name: Ensure /dev/shm is a tmpfs Mount
  ansible.posix.mount:
    path: "/dev/shm"
    src: "tmpfs"
    fstype: "tmpfs"
    opts: "defaults,rw,nosuid,nodev,noexec,relatime"
    state: mounted
  notify: Reboot
- name: Assert Host-Specific Mounts are Defined
  ansible.builtin.assert:
    that: filesystem_mounts_block | length > 0
    fail_msg: >-
      filesystem_mounts_block is empty
    success_msg: "{{ filesystem_mounts_block | map(attribute='path') | join(', ') }} defined."
- name: Enforce Partitions and Mount Options
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype | default('ext4') }}"
    opts: "{{ item.opts | default('defaults') }}"
    state: mounted
  loop: "{{ filesystem_mounts_block }}"
  loop_control:
    label: "{{ item.path }} ({{ item.src }})"
  notify: Reboot
