---
prod:
  children:
    proxmox:
      hosts:
        cyclops.homelab.zezura.cc:
          ansible_host: 192.168.1.2
    debian_13:
      hosts:
        cyclops.homelab.zezura.cc:
all:
  children:
    prod:
