---
- name: Ensure sshd Service is Unmasked, Enabled, and Running
  ansible.builtin.systemd_service:
    name: "chrony"
    masked: false
    enabled: true
    state: started
- name: Ensure the Ansible Control-Node Key is in Root's authorized_keys
  ansible.posix.authorized_key:
    user: root
    key: "{{ lookup('file', ansible_ssh_public_key_file) }}"
    state: present
- name: Deploy Hardened sshd_config
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
    validate: "/usr/sbin/sshd -t -f %s"
    backup: true
  notify: Restart sshd
- name: Remove Extra SSHD Configuration Directory
  ansible.builtin.file:
    path: "/etc/ssh/sshd_config.d"
    state: absent
  notify: Restart sshd
- name: Find SSH private host keys
  ansible.builtin.find:
    paths: /etc/ssh
    patterns: ["ssh_host_*_key"]
    file_type: file
  register: ssh_server_priv_keys
- name: Restrict SSH Private Host Keys
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: file
    owner: root
    group: root
    mode: "0600"
  loop: "{{ ssh_server_priv_keys.files }}"
  loop_control:
    label: "{{ item.path }}"
- name: Find SSH Public Host Keys
  ansible.builtin.find:
    paths: /etc/ssh
    patterns: ["ssh_host_*_key.pub"]
    file_type: file
  register: ssh_server_pub_keys
- name: Restrict SSH Public Host Keys
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: file
    owner: root
    group: root
    mode: "0644"
  loop: "{{ ssh_server_pub_keys.files }}"
  loop_control:
    label: "{{ item.path }}"
