---
- name: Set fs.protected_hardlinks
  ansible.posix.sysctl:
    name: fs.protected_hardlinks
    value: '1'
    sysctl_file: '{{ files.sysctl.fs }}'
    sysctl_set: true
    state: present
    reload: true
- name: Set fs.protected_symlinks
  ansible.posix.sysctl:
    name: fs.protected_symlinks
    value: '1'
    sysctl_file: '{{ files.sysctl.fs }}'
    sysctl_set: true
    state: present
    reload: true
- name: Set fs.suid_dumpable
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: '0'
    sysctl_file: '{{ files.sysctl.fs }}'
    sysctl_set: true
    state: present
    reload: true
