---
- name: Ensure AppArmor is Installed
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  loop: [apparmor, apparmor-utils]
- name: Set kernel.apparmor_restrict_unprivileged_unconfined
  ansible.posix.sysctl:
    name: kernel.apparmor_restrict_unprivileged_unconfined
    value: '1'
    sysctl_file: '{{ files.sysctl.kernel }}'
    sysctl_set: true
    state: present
    reload: true
  notify: Reboot
