---
- name: Ensure AppArmor is Installed
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  loop: [apparmor, apparmor-utils]
- name: Remove /etc/default/grub.d
  ansible.builtin.file:
    path: /etc/default/grub.d
    state: absent
- name: Remove apparmor=0 Grub Config Lines
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: (GRUB_CMDLINE_LINUX(?:_DEFAULT)?=".*?)\s*apparmor=0\s*(.*?")
    replace: \1\2
  notify: [Update Grub, Reboot]
- name: Set kernel.apparmor_restrict_unprivileged_unconfined
  ansible.posix.sysctl:
    name: kernel.apparmor_restrict_unprivileged_unconfined
    value: '1'
    sysctl_file: /etc/sysctl.d/60-kernel_sysctl.conf
    sysctl_set: true
    state: present
    reload: true
  notify: Reboot
