---
- name: Deploy Kernel Command-Line Hardening Drop-In
  ansible.builtin.template:
    src: 99-default.cfg.j2
    dest: "/etc/default/grub.d/99-default.cfg"
    owner: root
    group: root
    mode: "0644"
  notify: [Update Grub Config, Reboot]
- name: Keep --unrestricted on Generated Menuentries
  ansible.builtin.replace:
    path: "/etc/grub.d/10_linux"
    regexp: '^(CLASS="(?:(?!--unrestricted).)*?)"\s*$'
    replace: '\1 --unrestricted"'
  notify: [Update Grub Config, Reboot]
- name: Deploy Bootloader Password
  ansible.builtin.template:
    src: 40_cis_password.j2
    dest: "/etc/grub.d/40_cis_password"
    owner: root
    group: root
    mode: "0755"
  notify: [Update Grub Config, Reboot]
- name: Ensure Access to the Bootloader Config is Restricted
  ansible.builtin.file:
    path: "/boot/grub/grub.cfg"
    state: file
    owner: root
    group: root
    mode: "0600"
