---
- name: Configure /etc/motd
  ansible.builtin.copy:
    dest: /etc/motd
    content: "{{ warning_banners_text | trim + '\n' }}"
    owner: root
    group: root
    mode: "0644"
- name: Configure /etc/issue
  ansible.builtin.copy:
    dest: /etc/issue
    content: "{{ warning_banners_text | trim + '\n' }}"
    owner: root
    group: root
    mode: "0644"
- name: Configure /etc/issue.net
  ansible.builtin.copy:
    dest: /etc/issue.net
    content: "{{ warning_banners_text | trim + '\n' }}"
    owner: root
    group: root
    mode: "0644"
