---
# CIS Debian 13 Benchmark 7.2 - Local User and Group Settings.
- name: Ensure Local User and Group Database is Consistent
  ansible.builtin.script:
    cmd: user-group-audit.sh
  register: system_maintenance_user_group
  changed_when: false
  failed_when: "'** FAIL **' in system_maintenance_user_group.stdout" # 7.2.1-7.2.8
- name: Ensure Local Interactive User Home Directories are Configured
  ansible.builtin.script:
    cmd: user-home-directories.sh
  register: system_maintenance_home_dirs
  changed_when: >-
    'No modification needed to local interactive users home directories'
    not in system_maintenance_home_dirs.stdout
- name: Ensure Local Interactive User Dot Files Access is Configured
  ansible.builtin.script:
    cmd: user-dot-files.sh
  register: system_maintenance_dot_files
  changed_when: system_maintenance_dot_files.stdout | trim | length > 0
