---
- name: Remove Unrequired Kernel Modules
  hosts: proxmox
  tasks:
    - name: Remove Unrequired Filesystem Kernel Modules
      ansible.builtin.import_role:
        name: kernel-modules
        tasks_from: filesystem-modules.yml
- name: Configure Filesystem
  hosts: proxmox
  tasks:
    - name: Set Mount Options
      ansible.builtin.import_role:
        name: filesystem
        tasks_from: mount-options.yml
- name: Configure APT
  hosts: proxmox
  tasks:
    - name: Ensure Correct Services
      ansible.builtin.import_role:
        name: apt
        tasks_from: sources.yml
    - name: Ensure Correct Access
      ansible.builtin.import_role:
        name: apt
        tasks_from: directory-access.yml
    - name: Upgrade System
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe
        autoremove: true
        autoclean: true
        purge: true
    - name: Ensure Removed
      ansible.builtin.import_role:
        name: apt
        tasks_from: ensure_removed.yml
- name: Configure AppArmor
  hosts: proxmox
  tasks:
    - name: Configure AppArmor
      ansible.builtin.import_role:
        name: app-armor
- name: Configure Grub
  hosts: proxmox
  tasks:
    - name: Configure Grub Superuser
      ansible.builtin.import_role:
        name: grub
        tasks_from: secure-grub.yml
- name: Configure Sysctl
  hosts: proxmox
  tasks:
    - name: Configure Filesystem Sysctl
      ansible.builtin.import_role:
        name: sysctl
        tasks_from: fs.yml
    - name: Configure Kernel Sysctl
      ansible.builtin.import_role:
        name: sysctl
        tasks_from: kernel.yml
- name: Configure Security Limits
  hosts: proxmox
  tasks:
    - name: Configure Security Limits
      ansible.builtin.import_role:
        name: security
        tasks_from: limits.yml
