---
- name: Ensure Module Not Loaded
  community.general.modprobe:
    name: '{{ item }}'
    state: absent
    persistent: absent
  loop: '{{ kernel_modules.filesystem_modules.disabled }}'
- name: Copy Module Config
  ansible.builtin.copy:
    src: 60-{{ item }}.conf
    dest: /etc/modprobe.d/60-{{ item }}.conf
    mode: '0644'
  loop: '{{ kernel_modules.filesystem_modules.disabled }}'
