---
- name: Ensure cramfs Not Loaded
  community.general.modprobe:
    name: cramfs
    state: absent
    persistent: absent
- name: Copy 60-cramfs.conf
  ansible.builtin.copy:
    src: 60-cramfs.conf
    dest: /etc/modprobe.d/60-cramfs.conf
    mode: '0644'
- name: Ensure freevxfs Not Loaded
  community.general.modprobe:
    name: freevxfs
    state: absent
    persistent: absent
- name: Copy 60-freevxfs.conf
  ansible.builtin.copy:
    src: 60-freevxfs.conf
    dest: /etc/modprobe.d/60-freevxfs.conf
    mode: '0644'
- name: Ensure hfs Not Loaded
  community.general.modprobe:
    name: hfs
    state: absent
    persistent: absent
- name: Copy 60-hfs.conf
  ansible.builtin.copy:
    src: 60-hfs.conf
    dest: /etc/modprobe.d/60-hfs.conf
    mode: '0644'
- name: Ensure hfsplus Not Loaded
  community.general.modprobe:
    name: hfsplus
    state: absent
    persistent: absent
- name: Copy 60-hfsplus.conf
  ansible.builtin.copy:
    src: 60-hfsplus.conf
    dest: /etc/modprobe.d/60-hfsplus.conf
    mode: '0644'
- name: Ensure jffs2 Not Loaded
  community.general.modprobe:
    name: jffs2
    state: absent
    persistent: absent
- name: Copy 60-jffs2.conf
  ansible.builtin.copy:
    src: 60-jffs2.conf
    dest: /etc/modprobe.d/60-jffs2.conf
    mode: '0644'
- name: Ensure firewire-core Not Loaded
  community.general.modprobe:
    name: firewire-core
    state: absent
    persistent: absent
- name: Copy 60-firewire-core.conf
  ansible.builtin.copy:
    src: 60-firewire-core.conf
    dest: /etc/modprobe.d/60-firewire-core.conf
    mode: '0644'
- name: Ensure usb-storage Not Loaded
  community.general.modprobe:
    name: usb-storage
    state: absent
    persistent: absent
- name: Copy 60-usb-storage.conf
  ansible.builtin.copy:
    src: 60-usb-storage.conf
    dest: /etc/modprobe.d/60-usb-storage.conf
    mode: '0644'
- name: Ensure cifs Not Loaded
  community.general.modprobe:
    name: cifs
    state: absent
    persistent: absent
- name: Copy 60-cifs.conf
  ansible.builtin.copy:
    src: 60-cifs.conf
    dest: /etc/modprobe.d/60-cifs.conf
    mode: '0644'
- name: Ensure exfat Not Loaded
  community.general.modprobe:
    name: exfat
    state: absent
    persistent: absent
- name: Copy 60-exfat.conf
  ansible.builtin.copy:
    src: 60-exfat.conf
    dest: /etc/modprobe.d/60-exfat.conf
    mode: '0644'
- name: Ensure ext Not Loaded
  community.general.modprobe:
    name: ext
    state: absent
    persistent: absent
- name: Copy 60-ext.conf
  ansible.builtin.copy:
    src: 60-ext.conf
    dest: /etc/modprobe.d/60-ext.conf
    mode: '0644'
- name: Ensure fscache Not Loaded
  community.general.modprobe:
    name: fscache
    state: absent
    persistent: absent
- name: Copy 60-fscache.conf
  ansible.builtin.copy:
    src: 60-fscache.conf
    dest: /etc/modprobe.d/60-fscache.conf
    mode: '0644'
- name: Ensure gfs2 Not Loaded
  community.general.modprobe:
    name: gfs2
    state: absent
    persistent: absent
- name: Copy 60-gfs2.conf
  ansible.builtin.copy:
    src: 60-gfs2.conf
    dest: /etc/modprobe.d/60-gfs2.conf
    mode: '0644'
- name: Ensure nfs_common Not Loaded
  community.general.modprobe:
    name: nfs_common
    state: absent
    persistent: absent
- name: Copy 60-nfs_common.conf
  ansible.builtin.copy:
    src: 60-nfs_common.conf
    dest: /etc/modprobe.d/60-nfs_common.conf
    mode: '0644'
- name: Ensure nfsd Not Loaded
  community.general.modprobe:
    name: nfsd
    state: absent
    persistent: absent
- name: Copy 60-nfsd.conf
  ansible.builtin.copy:
    src: 60-nfsd.conf
    dest: /etc/modprobe.d/60-nfsd.conf
    mode: '0644'
- name: Ensure smbfs_common Not Loaded
  community.general.modprobe:
    name: smbfs_common
    state: absent
    persistent: absent
- name: Copy 60-smbfs_common.conf
  ansible.builtin.copy:
    src: 60-smbfs_common.conf
    dest: /etc/modprobe.d/60-smbfs_common.conf
    mode: '0644'
