---
- name: Copy Default Grub Config
  ansible.builtin.copy:
    src: default.conf
    dest: /etc/default/grub.conf
    mode: '0644'
  notify: [Update Grub, Reboot]
- name: Ensure Access to /boot/grub/grub.cfg
  ansible.builtin.file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: '0771'
