---
- name: Ensure Access to /boot/grub/grub.cfg
  ansible.builtin.file:
    path: /boot/grub/grub.cfg
    owner: root
    group: root
    mode: '0771'
- name: Deploy Custom Grub Superuser/Password Config
  ansible.builtin.template:
    src: 01-custom-auth.j2
    dest: /etc/grub.d/01-custom-auth
    owner: root
    group: root
    mode: '0755'
  notify: Update Grub
