---
- name: Ensure prelink and Automatic Error Reporting are not Installed
  ansible.builtin.apt:
    name: [prelink, apport]
    state: absent
    purge: true
    autoremove: true
- name: Ensure a Hard Limit on Core File Size
  ansible.builtin.copy:
    src: coredump-limits.conf
    dest: /etc/security/limits.d/60-coredump.conf
    owner: root
    group: root
    mode: "0644"
- name: Ensure systemd-coredump Drop-In Directory Exists
  ansible.builtin.file:
    path: /etc/systemd/coredump.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: Configure systemd-coredump to Discard Core Dumps
  ansible.builtin.copy:
    src: coredump.conf
    dest: /etc/systemd/coredump.conf.d/60-default.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd-coredump
